### ISSUE TITLE
Follow the XDG directory spec for .heroku

### ISSUE THREAD

**Issue by jasonkarns** [heroku/toolbelt#115]
Should be good citizens and following the XDG base directory spec: using `$XDG_DATA_HOME/heroku`, `$XDG_CACHE_HOME/heroku` and `$XDG_CONFIG_HOME/heroku` instead of dumping everything in `$HOME/.heroku`

reference spec: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by JakeChampion** [comment]
:+1: Please be a good citizen

**Comment by dickeyxxx** [comment]
https://github.com/heroku/heroku/pull/1807

**Comment by dickeyxxx** [comment]
https://github.com/heroku/heroku-cli/pull/120

**Comment by jasonkarns** [comment]
What kinds of files are stored in `app_dir`? Is `XDG_DATA_HOME` the correct location or should we also consider `XDG_CACHE_HOME` and `XDG_CONFIG_HOME`?

Should we also check if the relevant xdg directory exists? Per the spec, the XDG_* variables aren't required to be set, since they each have default values. I would expect that the XDG dirs be used if either 1) the XDG_* var is set *or* 2) the default XDG dir exists

Of course, the migration for heroku is more complicated because the files are not only read but written. I think following the same logic that git uses for determining the config location would be appropriate.

(posting comments here since they apply to both https://github.com/heroku/heroku/pull/1807 and https://github.com/heroku/heroku-cli/pull/120

**Comment by dickeyxxx** [comment]
The content is plugin code, log files, and node which is a runtime dependency. After reading the spec it seems that `XDG_DATA_HOME` is an appropriate use for all of this stuff. Arguably some stuff could be split into cache, but those files are short-lived and it would create problems if the variables were on different drives (since I can't just rename a file to move it). In general I'm opposed to splitting up this directory since having multiple directories is a nontrivial amount of work that could cause issues trying to roll out.

A `mkdir -p` is done to create the directory, so it will be created if it does not exist. If the variable isn't set it's going to fall back to the home directory. I don't think it would be a good idea to go hunting for the directory if the env var isn't set, that could be a clear intention by the user not to use it.

**Comment by jasonkarns** [comment]
> In general I'm opposed to splitting up this directory

Gotcha, that makes sense.



> If the variable isn't set  [... ] that could be a clear intention by the user not to use it.

I disagree. I believe it's quite common for people to use the xdg directory scheme without setting the variables if they use the defaults. I personally only set the variables for the directories which are *not* the default, but I still want the XDG directories used.

I propose:

```
if windows && localappdata -> localappdata
if xdg_data_home -> xdg_data_home
if exists(~/.local/share) -> ~/.local/share
else -> ~/.heroku
```

I would argue that the existence of the default XDG directory location is an explicit opt-in to xdg. As a user, I would be surprised if I had to explicitly set a variable to its spec-defined default value, just so it takes effect.

There is an alternative, however, which I believe is the way git works. (which had to support the transition from `~/.gitconfig` to `~/.config/git/config`)

```
if windows && localappdata -> localappdata
if exists(~/.heroku) -> ~/.heroku
else -> xdg_data_home || ~/.local/share
```

This way, existing installations would continue to use .heroku and no migration is necessary. And it makes XDG the default moving forward, and follows the spec (including default values).

**Comment by dickeyxxx** [comment]
The existence of a directory isn't a good enough heuristic to determine where to put the data. If on OSX I just created that directory, I would be surprised if all my plugins disappeared.

**Comment by jasonkarns** [comment]
That's fair. So the second snippet should be modified to .heroku for some
of the files that are normally put there.

XDG by default in all cases *except* where existing ~/.heroku is being used.

**Comment by dickeyxxx** [comment]
If a user wants to use the XDG spec they can declare it with an environment variable. Otherwise I'm not going to change the directory.
