### ISSUE TITLE
Hashes appended to bash prompt

### ISSUE THREAD

**Issue by joshuabaker** [heroku/toolbelt#121]
Three hashes were added to my bash prompt as a result of the installer.

<img src="http://i.imgur.com/32hrCMA.jpg">

Perhaps check for content length and prepend a newline before writing the extra lines?

**Comment by dickeyxxx** [comment]
thanks for submitting! https://github.com/heroku/heroku/pull/1356

**Comment by joshuabaker** [comment]
:wink::+1:
