### ISSUE TITLE
Heroku toolbelt auto update redirecting update message to stderr

### ISSUE THREAD

**Issue by stalluri** [heroku/toolbelt#124]
Shouldn't the auto update messages be redirected to stdout or autoupdate.log instead of stderr?

Our scripts which use heroku CLI internally are having trouble detecting whether heroku command ran successfully or not because of this behavior

**Comment by dickeyxxx** [comment]
It should be on stderr. stdout is only supposed to be used for standard output. If the messages were on stdout then it would be difficult to script the output.

Are you checking to see if there is any content in stderr and determining if it's an error for that reason? You should check the exit codes instead.

**Comment by stalluri** [comment]
Our scripts check both exit codes and stderr to check for errors.

Since the update message is going to ~/.heroku/autoupdate.log , why the need for stderr ?

**Comment by dickeyxxx** [comment]
people aren't likely to see the update message going to the update log. You should stick to exit codes, stderr is an appropriate place for these warnings.

**Comment by stalluri** [comment]
Dickey, 

I couldn't find a way to disable auto-update and do a manual update once in a while. Can you help me with that?

thanks
Satish

**Comment by dickeyxxx** [comment]
right now there isn't a way to disable the autoupdater

**Comment by stalluri** [comment]
Thanks
