### ISSUE TITLE
open: no such file or directory

### ISSUE THREAD

**Issue by foxx** [heroku/toolbelt#125]
There is a weird problem...

```
$ heroku git:remote -a XXXXX-website-prod -r heroku-prod
Enter your Heroku credentials.
Email: XXXX
Password (typing will be hidden):
 ▸    open : no such file or directory
```

```
$ heroku --version
heroku-toolbelt/3.37.0 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.19.21-4f4a75d (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-git@2.2.1
heroku-status@1.2.0
```

There is no debugging or verbose options, nor any context to explain what this error is in relation to. The `.git` directory is present and accessible.

**Comment by dickeyxxx** [comment]
try updating, this should be fixed in 3.37.1

**Comment by foxx** [comment]
Same problem;

```

$ heroku git:remote -a XXXXX-website-prod -r heroku-prod
Installing Heroku Toolbelt v4... done
Installing plugin heroku-git... done
Enter your Heroku credentials.
Email: XXXXX
Password (typing will be hidden):
 ▸    open : no such file or directory
make: *** [pushprod] Error 1
```

```
foxx:XXXXX foxx$ heroku version
heroku-toolbelt/3.37.1 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.19.23-802a7d4 (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-git@2.2.2
```

**Comment by foxx** [comment]
For future ref, I was able to temporarily get around this problem by using git commands instead. Not an ideal solution, but it works for now until Heroku devs can test their changes locally ;)

```
$ git remote -v | egrep -q "^heroku-dev" || \
    git remote add heroku-dev git@heroku.com:XXXXXX-website-dev.git
```

**Comment by dickeyxxx** [comment]
can you send me the last few lines of `~/.heroku/error.log`?

**Comment by foxx** [comment]
Sure, here you go;

```
$ tail ~/.heroku/error.log -n 100
2015/05/20 13:36:08 setting up iojs 2.0.2
2015/05/20 13:36:21 done setting up iojs
2015/05/20 13:36:22 Installing plugin heroku-git...
2015/05/20 13:36:28 done
2015/05/20 13:36:28 Email:
2015/05/20 13:36:48  ▸    open : no such file or directory
```

**Comment by foxx** [comment]
Sure, here you go;

```
$ tail ~/.heroku/error.log -n 100
2015/05/20 13:36:08 setting up iojs 2.0.2
2015/05/20 13:36:21 done setting up iojs
2015/05/20 13:36:22 Installing plugin heroku-git...
2015/05/20 13:36:28 done
2015/05/20 13:36:28 Email:
2015/05/20 13:36:48  ▸    open : no such file or directory
```

**Comment by dickeyxxx** [comment]
can you try again? I think I fixed this now. It was an issue with 32-bit linux

**Comment by foxx** [comment]
Same problem.

```
foxx:~ foxx$ heroku version
heroku-toolbelt/3.37.1 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.19.25-3146aad (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-git@2.2.3
```

Experiencing this problem both on a clean trusty64 install, and on Yosemite.

**Comment by dickeyxxx** [comment]
ah I was able to reproduce, this is an issue with login, not with git:remote. Hang on.

**Comment by dickeyxxx** [comment]
okay, v4.19.27 will have the fix for this. Sorry about the runaround!

**Comment by foxx** [comment]
No worries, that seems to be working now :)

May I make two suggestions;

* Introduce CLI tests to prevent regressions
* Add a --debug or --stacktrace option to dump extra debugging info in the event of an error

**Comment by dickeyxxx** [comment]
there are tests, they just don't test every situation. There is also debugging, you use the `HEROKU_DEBUG` env var

**Comment by foxx** [comment]
Then TDD hasn't been followed, sadly. CLIs are no different, they should be tested like everything else, otherwise the tool cannot be considered stable. Just my two cents.
