### ISSUE TITLE
New version broken on Ubuntu 15.04

### ISSUE THREAD

**Issue by andreafdaf** [heroku/toolbelt#126]
Heroku-toolbelt updated by itself just a while ago and stopped working completely. It simply doesn't work anymore, the CLI is totally irresponsive.

Even running
```
heroku --version
```
shows no output.

Files are where they are supposed to be. Which heroku seems to be ok
```
andrea@andrea-XPS-13:~/workspace/app-v1$ which heroku
/usr/local/heroku/bin/heroku
```

Already tried reinstalling with no luck. Any guesses?

**Comment by dickeyxxx** [comment]
could you delete `~/.heroku` and retry?

**Comment by dickeyxxx** [comment]
this is related to https://status.heroku.com/incidents/769 probably
just wait 120 seconds, it will start working again

**Comment by andreafdaf** [comment]
thanks a lot for pointing this out :)

waiting didn't changed anything but removing
```
~/.heroku/heroku-cli
```
brought everything back to normal, thanks again!
