### ISSUE TITLE
Homebrew version out of date

### ISSUE THREAD

**Issue by connorshea** [heroku/toolbelt#127]
Homebrew only has `heroku-toolbelt 3.37.7`, whereas when I use the Toolbelt it tells me to upgrade to 3.38.1. Using `heroku update` tells me to `!    Use 'brew upgrade heroku-toolbelt' to update`, but running `brew upgrade heroku-toolbelt` doesn't pull down any new version.

I assume this isn't supposed to be happening? Latest version of Homebrew, OS X Yosemite.

**Comment by dickeyxxx** [comment]
this is a homebrew issue

**Comment by connorshea** [comment]
Okay, that's not very helpful. Is it taking a while to propagate the new version out to users? Any idea when I'll be able to use the latest version? Should I switch to an install of Heroku Toolbelt outside of Homebrew?

**Comment by dickeyxxx** [comment]
homebrew is manually updated by the maintainers of that project, you'll need to wait until they update it

**Comment by connorshea** [comment]
ah, alright, thank you.
