### ISSUE TITLE
If I install the standalone download version .dmg of toolbelt it doesn't recognize my global rbenv ruby version.

### ISSUE THREAD

**Issue by ginolon** [heroku/toolbelt#132]
If I install the standalone download version .dmg of toolbelt it doesn't recognize my global rbenv ruby version.

If I use `brew install heroku` it recognize 2.2.3. How to fix?

**Comment by dickeyxxx** [comment]
this is by design, the toolbelt is supposed to run on `1.9.3`

**Comment by ginolon** [comment]
???? In the Getting Start docs on Heroku they say to install Ruby 2.2.3.

**Comment by dickeyxxx** [comment]
for your ruby app, not the toolbelt
