### ISSUE TITLE
Duplicate lines of text when --help is used

### ISSUE THREAD

**Issue by rosswilson** [heroku/toolbelt#135]
Passing `--help` to any topic, such as `heroku stack --help` results in the help text being duplicated twice:

```
Usage: heroku stack

show the list of available stacks

show the list of available stacks

 -a, --app APP       # app to run command against
 -r, --remote REMOTE # git remote of app to run command against
```

Note how "show the list of available stacks" is duplicated twice.

**Comment by dickeyxxx** [comment]
can you update and try again? What other topics did you see it on?

**Comment by rosswilson** [comment]
I've updated to the latest version:

```
heroku-toolbelt/3.42.17 (x86_64-darwin14) ruby/2.2.2
heroku-cli/4.25.3-15cf54c (amd64-darwin) go1.5.1
=== Installed Plugins
heroku-apps@0.3.2
heroku-cli-addons@0.0.2
heroku-fork@4.0.0
heroku-git@2.4.3
heroku-local@4.1.5
heroku-run@2.9.1
heroku-status@1.2.2
```

I found the duplicated lines on:

`stack --help`
`fork --help`
`local --help`
`maintenance --help`
`plugins --help` (duplicated 3 times)
`status --help`
`update --help`
`version --help`

Is there anything else that I can do you assist?

**Comment by dickeyxxx** [comment]
https://github.com/heroku/heroku-cli/pull/95
