### ISSUE TITLE
process.title / [eval]:7 - can't do heroku:set with multi-line values ( from a file )

### ISSUE THREAD

**Issue by clarkewd** [heroku/toolbelt#136]
to recreate, setup `/tmp/test` with multiple lines such as:

    a
    
    b

Then run ``heroku config:set TEST="`cat /tmp/test`"``

This results in:

	[eval]:7
			process.title = 'heroku config:set TEST=one
			                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

	SyntaxError: Unexpected token ILLEGAL
	    at Object.exports.runInThisContext (vm.js:53:16)
	    at Object.<anonymous> ([eval]-wrapper:6:22)
	    at Module._compile (module.js:435:26)
	    at node.js:576:27
	    at doNTCallback0 (node.js:417:9)
	    at process._tickCallback (node.js:346:13)

It seems like the values are not being escaped in this (binary) file: `~/.heroku/heroku-cli`

I attempted to escape the values via the command line but have been unsuccessful so far

**Comment by dickeyxxx** [comment]
can you update and try again? a fix went out for this earlier

**Comment by clarkewd** [comment]
I think I have the latest version. I used the installer from https://toolbelt.heroku.com/

On `OS X` here is some info about my versions - does this look right?

	$ which heroku
	/usr/local/bin/heroku

	$ heroku --version
	heroku-toolbelt/3.42.20 (x86_64-darwin10.8.0) ruby/1.9.3
	heroku-cli/4.27.1-b35d19d (amd64-darwin) go1.5.1

	=== Installed Plugins
	heroku-apps@0.5.1
	heroku-cli-addons@0.1.0
	heroku-fork@4.0.0
	heroku-git@2.4.3
	heroku-local@4.1.5
	heroku-oauth
	heroku-run@2.9.1
	heroku-status@1.2.2

**Comment by clarkewd** [comment]
Following the [uninstall instructions](https://devcenter.heroku.com/articles/heroku-command#uninstalling-the-heroku-cli) and then reinstalling the package from https://toolbelt.heroku.com/ seems to have fixed the issue for me. Maybe I could have run `heroku update` too. Thanks for the help.
