### ISSUE TITLE
`heroku config --shell` avoids quoting when output is piped

### ISSUE THREAD

**Issue by scribu** [heroku/toolbelt#144]
I'm trying to set up an environment for an integration test and `heroku config --shell` seems to produce almost exactly the output I need.

I have a few variables which actually contain JSON, and the command correctly adds single quotes around them:

```shell
$ heroku config --shell
MY_VAR='{"foo": "bar"}'
```

... except when I pipe the output to another command or to a file:

```shell
$ heroku config --shell -r prod | sed 's/^/export /g'
export MY_VAR={"foo": "bar"}
```

Aaargh!

Version info:

```shell
$ heroku version
heroku-toolbelt/3.42.20 (universal.x86_64-darwin15) ruby/2.0.0
heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2
```

**Comment by dickeyxxx** [comment]
this is now fixed
