### ISSUE TITLE
Allow non-interactive usage

### ISSUE THREAD

**Issue by cesarizu** [heroku/toolbelt#145]
When running any heroku toolbelt command in Heroku through a shell or a scheduled task I get the following prompt:

`Would you like to submit Heroku CLI usage information to better improve the CLI user experience?`

This breaks the automated scripts that I'm trying to use. Is there any way to suppress any interactive input that the toolbelt may need, like a `--non-interactive` flag or something similar?

**Comment by dickeyxxx** [comment]
can you show me an example of the script you're trying to run?

**Comment by cesarizu** [comment]
Initially I'm just running `heroku --version` just to output in the logs which version is running. But this is happening with any command I try to run as well.

**Comment by dickeyxxx** [comment]
But is it happening within a script? Because it shouldn't if it's not connected to a tty.

**Comment by dickeyxxx** [comment]
Also, it will only ever display once and it will automatically cancel if you don't press anything for a few seconds.

**Comment by cesarizu** [comment]
Some of this scripts we are running from a tty on demand and some using Heroku's scheduler. I noticed this when on of the scheduled tasks seemed not to be running. After trying from a tty I got that message. Responding Y or N let the script continue normally and it completed.

**Comment by cesarizu** [comment]
I just tried and you are right about that. In that case maybe I jumped to fast to a conclusion. I'll continue investigating this, maybe it was related to something else.

**Comment by tmecklem** [comment]
It pauses every one of my codeship ci builds for 20 seconds when I run a custom script command 'heroku maintenance:on ...' to put up the maintenance page.
