### ISSUE TITLE
Heroku Toolbelt messed up Git diffs

### ISSUE THREAD

**Issue by baconface** [heroku/toolbelt#155]
After installing Toolbelt my Git diffs are now incorrect. Instead of just the line which the changes appearing the whole document is in a diff. Very annoying and only started happening after installing Toolbelt and restarting.

Windows 8.1.

**Comment by baconface** [comment]
And why does Git need to be reinstalled anyways if it is already on the machine?

**Comment by baconface** [comment]
Reinstalling Git has fixed the issue for me. But the behavior of Toolbelt breaking this should still be looked into?

**Comment by ransombriggs** [comment]
@baconface I am sorry that the toolbelt installed over your previously installed version.  I plan on releasing a fix for this tomorrow so that other users do not encounter the same bug.

**Comment by ransombriggs** [comment]
I just released version `3.42.45` of the installer which will not install Git if it detects an existing installation.
