### ISSUE TITLE
Heroku `local` command now truncates output lines, with no option to enable wrapping instead

### ISSUE THREAD

**Issue by cee-dub** [heroku/toolbelt#157]
A recent update to the `local` command changed output formatting and forces line truncation, which can be nice sometimes, but makes Rails development mode query logging pretty much useless, since queries are often one long line.

Can you add a command line option to enable wrapping full lines?

**Comment by ransombriggs** [comment]
@cee-dub I looked into you issue and should be able to fix it, but I will have to push a change up to the underlying tool that we use, so it may take some time to resolve.

**Comment by cee-dub** [comment]
@ransombriggs Thanks for looking into it! Let me know if I can be of assistance. Which tool handles this internally?

**Comment by ransombriggs** [comment]
@cee-dub https://github.com/strongloop/node-foreman is the tool used internally.  I am looking into how the wrap & trim options work and am working on a way to turn off both.  I should have a pull request this afternoon, assuming no interruptions.

**Comment by ransombriggs** [comment]
@cee-dub I just filed a [pull request](https://github.com/strongloop/node-foreman/pull/98) with node-foreman to add a flag allowing me to turn off wrapping (there is an option already to turn off trimming, but it still wraps which would be problematic for you to copy SQL out of)

**Comment by dickeyxxx** [comment]
doesn't the `-w` flag fix this?

**Comment by ransombriggs** [comment]
@dickeyxxx the `-w` flag inserts a bunch of characters when it wraps, which makes it hard to copy logs out.  I would like to get it back to the same behavior as `forego` where it did not alter the log output at all.
```
rbriggs@ebriggs-ltm [02:52:58] [~] 
-> % cat Procfile                                             
web: ruby -e 'puts "0" * 1000'
rbriggs@ebriggs-ltm [02:53:01] [~] 
-> % nf start -w -- web
[WARN] No ENV file found
[OKAY] Wrapping display Output to 296 Columns
2:53:03 PM web.1 |  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2:53:03 PM web.1 |  >  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2:53:03 PM web.1 |  >  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2:53:03 PM web.1 |  >  0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[DONE] Killing all processes with signal  null
2:53:03 PM web.1 Exited Successfully
rbriggs@ebriggs-ltm [02:53:03]
```

**Comment by dickeyxxx** [comment]
this is changed now
