### ISSUE TITLE
"heroku run" does not correctly preserve arguments that include whitespaces

### ISSUE THREAD

**Issue by rasky** [heroku/toolbelt#51]
I need to executed a remote command that requires an argument that includes a space. For instance:
  
    heroku run ./manage.py foobar --option "my argument with spaces"

This does not work correctly because the run command basically flats the whole command line into a string, see run.rb:

```ruby
def index
  command = args.join(" ")
  error("Usage: heroku run COMMAND")if command.empty?
  run_attached(command)
end
```

The command output is:

    Running `./manage.py foobar --option my argument with spaces` attached to terminal... up, run.3905

that shows that the single argument has basically been flatten to multiple commands.

The run command should preserve the existing argument list the way the original shell has parsed them and use a spawn command that accepts an argument list rather than a command line, or alternatively (if it's really required, but it shouldn't) rebuild a bash-escaped command line by using a bash emulation library (with proper escaping / quoting).

**Comment by dickeyxxx** [comment]
this is fixed in the new version of run. Right now you can use it with `heroku run --exit-code`. Soon it will be default.
