### ISSUE TITLE
Need uninstall instructions/script for OSX

### ISSUE THREAD

**Issue by ddollar** [heroku/toolbelt#8]

**Comment by redbar0n** [comment]
+1

**Comment by Aweary** [comment]
Is there any word on this?

**Comment by jonmountjoy** [comment]
Check out the uninstall instructions that are [now documented here](https://devcenter.heroku.com/articles/heroku-command#uninstalling-the-heroku-cli).  

Feel free to leave comments (click "let us know" at the bottom) if that fails!

Thanks!
Jon
