### ISSUE TITLE
Unattended install in Windows gets locked without UI

### ISSUE THREAD

**Issue by pjmolina** [heroku/toolbelt#94]
When making an unattended administrative install in Windows (no UI) (invoking with parameter ```/verysilent``` ) the installer get stuck.

Digging down a little further: the cause seems to be the git installer.
Heroku-toolbelt installer calls git install with ```/silent``` parameter. 
Nevertheless, this mode seems to be not silent enough and the git installer shows windows on screen and get blocked if no UI is available.

Possible fix: Calling to git installer with ```/verysilent``` seems to solve it.

Regression test sample: install heroku-toolbelt with ```/verysilent``` parameter on an Azure WorkerRole Setup script.

**Comment by pjmolina** [comment]
Using the `heroku-toolbelt` installer for windows version `3.42.27` this issue has re-appeared again.

**Comment by dickeyxxx** [comment]
this is done
